import os

BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
TRANSACTIONS_TOPIC = os.getenv("KAFKA_TOPIC_TRANSACTIONS", "transactions")
PRODUCE_INTERVAL = float(os.getenv("PRODUCE_INTERVAL_SEC", "0.5"))